from typing import Final

STOP_INFORMATION: Final = "Stop Information"
STOP_NAME: Final = "Stop Name"
STOP_FAMILY: Final = "Stop Family"
NUMBER_RANKS: Final = "Number of Ranks"
RANK_INFORMATION: Final = "Rank Information"
RANK_NUMBER: Final = "Rank Number"
RANK_SIZE: Final = "Rank Size"
NUMBER_PIPES: Final = "Number of Pipes"
STARTING_NOTE: Final = "Starting Note"
PIPE_INFORMATION: Final = "Pipe Information"
PIPE_CONSTRUCTION: Final = "Pipe Construction"
PIPE_TYPE: Final = "Pipe Type"
NUMBER_HARMONICS: Final = "Number of Harmonics"
PIPE_SETTINGS: Final = "Pipe Settings"
PIPE_NUMBER: Final = "Pipe Number"
ADSR_SETTINGS: Final = "ADSR Settings"
ATTACK_TIME: Final = "Attack Time"
DECAY_TIME: Final = "Decay Time"
SUSTAIN_LEVEL: Final = "Sustain Level"
RELEASE_TIME: Final = "Release Time"
AMPLITUDE: Final = "Amplitude"
HARMONIC_ADSR_SETTINGS: Final = "Harmonic ADSR Settings"